services:
  - type: web
    name: drawguess-skribbl-clone
    runtime: node
    plan: free
    buildCommand: npm install && npm --prefix client install && npm --prefix server install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
